# Generated by Django 2.1.2 on 2018-10-25 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReportTitle', models.CharField(max_length=256)),
                ('CurrentOffice', models.CharField(blank=True, default='', max_length=32, null=True)),
                ('CurrentState', models.CharField(blank=True, default='', max_length=32, null=True)),
                ('LastOffice', models.CharField(blank=True, default='', max_length=32, null=True)),
                ('NeedsReview', models.BooleanField(default=False)),
                ('WasSent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ReportFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specification', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ROUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Office', models.CharField(max_length=16)),
                ('Flow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.ReportFlow')),
                ('_User', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='Owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.ROUser'),
        ),
    ]
